name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:
jobs:
  stale:
    name: Mark PRs stale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-pr-message: 'This PR has no activity.'
          close-pr-message: 'This PR was closed because it has been stalled for 45 days with no activity.'
          days-before-pr-stale: 15
          days-before-pr-close: 45
          delete-branch: false
